Repository rafaeldcampbell/miocardio-pedriatra-paciente, pull requests merged in 2019-11, with the labels that each got.

#27 Adicionando internacionalização
  assets/res/string/string_en.json
  assets/res/string/string_pt.json
  lib/functions/navigatorBar.dart
  lib/localization.dart
  lib/login.dart
  lib/main.dart
  lib/pages/home.dart
  lib/pages/info.dart
  lib/pages/login.dart
  lib/pages/questionsPage.dart
  lib/pages/reminderPage.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: Priorizado, Teste

#28 Adicionando teste para transição de telas
  lib/functions/navigatorBar.dart
  lib/pages/home.dart
  lib/pages/info.dart
  lib/pages/login.dart
  lib/pages/questionsPage.dart
  lib/pages/reminderPage.dart
  pubspec.lock
  pubspec.yaml
  test/transicao_test.dart
  test/widget_test.dart
Labels: Teste

#32 Removendo a tela de login
  assets/res/logo/logo - Copia.PNG
  assets/res/logo/logo.PNG
  assets/res/logo/logo.jpg
  assets/res/string/string_en.json
  assets/res/string/string_pt.json
  flutter_01.png
  flutter_02.png
  flutter_03.png
  lib/functions/localization.dart
  lib/functions/navigatorBar.dart
  lib/main.dart
  lib/pages/home.dart
  lib/pages/info.dart
  lib/pages/login.dart
  lib/pages/questionsPage.dart
  lib/pages/reminderPage.dart
  test/transicao_test.dart
  test/widget_test.dart
Labels: Teste

#33 Atualização dos Textos da Tela Perguntas Frequentes
  assets/res/string/string_en.json
  assets/res/string/string_pt.json
  pubspec.yaml
  test/widget_test.dart
Labels: Teste

#40 Adicionando calendário a tela de lembretes
  lib/pages/reminderPage.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: Banco de dados, Revisar, Teste

#42 Adicionando métodos para acesso ao banco de dados (para reminders)
  lib/database/dbConexion.dart
  lib/database/reminder.dart
  pubspec.lock
  pubspec.yaml
Labels: Banco de dados, Teste

#45 Adicionando cards à tela de lembretes
  lib/components/cardReminder.dart
  lib/database/dbConexion.dart
  lib/database/reminder.dart
  lib/pages/reminderPage.dart
  test/widget_test.dart
Labels: Melhoria

#46 Adicionando tela para criar lembretes
  assets/res/string/string_en.json
  assets/res/string/string_pt.json
  lib/pages/addReminderPage.dart
  lib/pages/reminderPage.dart
Labels: Priorizado, Revisar, Teste
